Refactor v0.4 suggestions for feature examples
FZJ-INM1-BDA/siibra-python pull request #252
Opened 2023-01-24 15:26 UTC by AhmetNSimsek

This branch includes some suggestions to enrich the examples of data features and add plot_matrix() method to display heatmaps of connectivity matrices.

2023-01-24 17:49 UTC, dickscheid requested changes

2023-01-24 17:49 UTC, dickscheid commented on examples/03_data_features/003_cell_distributions.py
> +layer1_cells = c[c["layer"]==1]
pandas provides even cleaner ways for this: `c[c.layer == 1]` or, which I prefer much,  `c.query('layer == 1')`

2023-01-24 17:49 UTC, dickscheid commented on examples/03_data_features/003_cell_distributions.py
> +    layer1_cells["x"], layer1_cells["y"],
same here, layer1_cells.x etc.

2023-01-24 17:49 UTC, dickscheid commented on examples/03_data_features/003_cell_distributions.py
> +mean_cell_area_layer_1 = layer1_cells["area(micron**2)"].mean()
just a style question, but I would avoid the extra line in this case, and put the mean() statement right in the f-string below - it is not much longer anyways.

2023-01-24 17:49 UTC, dickscheid commented on examples/03_data_features/006_connectivity_matrices.py
> +matrix.head()
what is this line doing?

2023-01-24 17:49 UTC, dickscheid commented on siibra/features/basetypes/regional_connectivity.py
> +            from numpy import log10
isn't numpy already imported as np? I'd guess so.

2023-01-24 17:49 UTC, dickscheid commented on siibra/features/basetypes/regional_connectivity.py
> +        subject_title = subject if subject is not None else ""
short form is `subject_title = subject or ""` I believe (since None is not True)

2023-01-24 17:49 UTC, dickscheid commented on siibra/features/basetypes/regional_connectivity.py
> +        kwargs["figure"] = kwargs.get("figure", (15, 15))
"figure" as a plot argument appears strange to me, do matplotlib or nilearn plots have such an argument?  what you provide, the tuple (15, 15); also looks more like figsize to me - for "figure" I would expect a figure object

2023-01-24 20:46 UTC, AhmetNSimsek commented on siibra/features/basetypes/regional_connectivity.py
> +        kwargs["figure"] = kwargs.get("figure", (15, 15))
I was surprised as well but that is how nilern.plot_matrix lists the parameter. It can take `matplotlib.figure.Figure` or  `figsize :obj: tuple`. (There are dedicated methods within to use the correct type for correct usage.)

2023-01-24 20:52 UTC, AhmetNSimsek reviewed
Pushed a commit with the changes and noted the use of "figure" in conversation.

2023-01-25 13:17 UTC, xgui3783 commented on siibra/features/basetypes/regional_connectivity.py
> +    def plot_matrix(self, subject: str = None, regions: list[str] = None, logscale: bool = False, **kwargs):
this will need to be `List[str]`, or else it will fail in python < 3.10 (I think)

2023-01-25 13:24 UTC, AhmetNSimsek commented on siibra/features/basetypes/regional_connectivity.py
> +    def plot_matrix(self, subject: str = None, regions: list[str] = None, logscale: bool = False, **kwargs):
You are right, I will push a fix now

2023-01-31 17:16 UTC, dickscheid commented on examples/03_data_features/003_cell_distributions.py
> +# Having the data in data frame format allows further flexibility such as:
good idea

2023-01-31 17:19 UTC, dickscheid approved these changes

2023-01-31 17:20 UTC, merged