Add spatial feature class
FZJ-INM1-BDA/siibra-python pull request #399
Opened 2023-06-22 09:08 UTC by AhmetNSimsek

Aims of this PR:
- [ ] Add a feature base class `spatial` that handles features with location anchors.
- [ ] Replace bounding box calculation of image features with precomputed bounding box coordinates in the configuration.
    - [ ] Remove the need for ImageAnchor
- [ ] Add a pointset spatial feature subclass that handles data such as big brain intensity that is delivered in coordinates and corresponding series of values.
- [ ] Refactor big brain intensity feature #377
    - [ ] Return data as one dataframe of all the coordinates inside the region map
    - [ ] Ensure it is deterministic, #295 
    - [ ] Get the regional map in BigBrain space if the region is supported there
    - [ ] Regional maps of lower-level structures should still be collected from the same space for consistency.
    - [ ] Query for a higher level structure should return one result not a list of combined results for its leaves
    - [ ] Intensity calculation for the right hemisphere must be included
         - [ ] Write the supporting code
         - [ ] Data source should be clarified with Konrad Wagstyl

2023-06-27 09:11 UTC, xgui3783 requested changes

2023-06-27 09:11 UTC, xgui3783 commented on siibra/features/image/image.py
> +            space_spec=anchor.space.id,
I would check None'ness of anchor.space, or this line could raise

2023-06-27 09:11 UTC, xgui3783 commented on siibra/features/tabular/bigbrain_intensity_profile.py
> +    spatial.PointCloud,
shouldn't this also subclass CorticalProfile?

2023-06-27 09:11 UTC, xgui3783 commented on siibra/features/tabular/bigbrain_intensity_profile.py
> +    def _check_sanity(self):
ditto, see above (code repetition would mean something is fishy)

2023-06-27 09:11 UTC, xgui3783 commented on siibra/features/tabular/bigbrain_intensity_profile.py
> +    def assign_layer(self, coordinate, depth: float):
ditto, see above (code repetition would mean something is fishy)

2023-06-29 06:27 UTC, AhmetNSimsek commented on siibra/features/tabular/bigbrain_intensity_profile.py
> +    spatial.PointCloud,
Cortical profile will be removed completely. That is one of the things I wanted to talk about.

2023-06-29 12:52 UTC, AhmetNSimsek commented on siibra/features/tabular/bigbrain_intensity_profile.py
> +    spatial.PointCloud,
ReceptorDensityProfile uses plot, data, and _check_sanity of CortialProfile. All these will need to change for CellDensity and BigBrainIntensity under one roof (that is another thing to talk about in terms of design). Then, what is needed for ReceptorDensityProfile could just be within ReceptorDensityProfile from CortialProfile.
This is of course just one idea.

2023-06-29 12:55 UTC, xgui3783 commented on siibra/features/tabular/bigbrain_intensity_profile.py
> +    spatial.PointCloud,
So your proposal is Receptor Density Profile will subclass Tabular directly?

2023-06-29 12:56 UTC, AhmetNSimsek commented on siibra/features/tabular/bigbrain_intensity_profile.py
> +    spatial.PointCloud,
Indeed

2023-06-29 13:18 UTC, AhmetNSimsek commented on siibra/features/tabular/bigbrain_intensity_profile.py
> +    spatial.PointCloud,
I see what you mean. I was thinking if ReceptorDensityProfile is the only class that is using CortialProfile elements, why not carry it there? There are a few constants Layerwise-* features use but we could just as well pull them from ReceptorDensityProfile. While BigbrainIntesityProfile (in this branch) has more or less repeated code (not the final version), it differs from CortialProfile and requires overriding the method either way. So this makes CortialProfile less useful.

I will take another look to see if I can make changes in CortialProfile for catering to a broader range and preserve the existing structure, except for adding PointCloud base to BigbrainIntensityProfile and CellDensityProfile.

2023-06-29 13:22 UTC, xgui3783 commented on siibra/features/tabular/bigbrain_intensity_profile.py
> +    spatial.PointCloud,
This actually could also be breaking old code. e.g:

```python
siibra.features.get('hoc1 left', 'cortical profile')
```

would fetch receptor profile + layerwise intensity. would fail with the proposed change

2023-07-05 12:12 UTC, AhmetNSimsek commented
Code snippet to see the changes in BigBrainIntensityProfile
```python
import siibra
fts = siibra.features.get(siibra.get_region('2.9', 'occipital lobe'), siibra.features.cellular.BigBrainIntensityProfile)
print(len(fts))
f = fts[0]
print(f.data)
f.plot()
f.plot(point=67, backend='plotly')
```

2023-07-12 12:54 UTC, AhmetNSimsek commented
IMPORTANT: before merging, the commit a968ac74f388921fa2f76864057a4e57c0e26fee must be reverted. It was only made to simplify testing.

2023-07-12 13:03 UTC, AhmetNSimsek commented
This PR has been converted to draft only because it is considered to be breaking for v0.4. It might be prudent to create a new branch for v0.5 (which this branch could be the starter of) and develop this further there. This also implies the need for a v0.4 end-of-life branch.

2023-08-18 11:16 UTC, AhmetNSimsek commented
Test: time getting image section instances (after initializing maps, parcellations, and spaces).
| | No local cache | Cached on disk | 
| --- | --- | --- |
| Read bbox (a968ac74f388921fa2f76864057a4e57c0e26fee) |  (19.1s, 19.1s, 18.9s) | (0.151s, 0.178s, 0.155s)  |
| Current (4057d1a47a0a88b71bcc7433218cdb01c9a2aad9) | (19s, 18.5s, 18.7s)  | (0.189s, 0.135s, 0.085s)  |

2023-08-21 15:05 UTC, closed without merging